spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        jdbc:
          batch_size: 100000

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:root}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/demo}
springdoc:
  swagger-ui:
    url: /openapi/demo-api.yml
    path: docs
    disable-swagger-default-url: true
